# Generated by Django 5.0.6 on 2024-06-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0006_alter_tests_options_subjects_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_stage', to='subjects.subjects', unique=True)),
                ('second_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_stage', to='subjects.subjects', unique=True)),
            ],
        ),
    ]
