# Generated by Django 5.0.6 on 2024-06-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('subjects', '0007_alter_answers_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocksubject',
            name='first_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_stage', to='subjects.subjects'),
        ),
        migrations.AlterField(
            model_name='blocksubject',
            name='second_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_stage', to='subjects.subjects'),
        ),
    ]
