# Generated by Django 5.0.6 on 2024-06-26 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_blocksubject_first_stage_and_more'),
        ('subjects', '0007_alter_answers_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.BooleanField(default=False)),
                ('q_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_body', to='subjects.tests')),
                ('t_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_body', to='subjects.answers')),
            ],
        ),
    ]
