# Generated by Django 5.0.6 on 2024-06-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
