# Generated by Django 5.0.6 on 2024-06-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocksubject',
            name='second_stage',
        ),
    ]
