# Generated by Django 5.0.6 on 2024-06-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_blocksubject_second_stage'),
        ('subjects', '0007_alter_answers_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockSubject',
            new_name='FirstSubject',
        ),
        migrations.CreateModel(
            name='SecondSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_subject', to='subjects.subjects')),
            ],
        ),
    ]
