# Generated by Django 5.0.6 on 2024-06-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_blocktest'),
        ('subjects', '0007_alter_answers_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktest',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='subjects.subjects'),
        ),
        migrations.AlterField(
            model_name='blocktest',
            name='second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='subjects.subjects'),
        ),
    ]
