# Generated by Django 5.0.6 on 2024-07-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_blocktest_first_alter_blocktest_second'),
        ('subjects', '0008_alter_answers_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_point', models.FloatField(default=2.1)),
                ('subject_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_quiz', to='subjects.subjects')),
                ('test_quiz', models.ManyToManyField(related_name='test_quiz', to='subjects.tests')),
            ],
        ),
    ]
