# Generated by Django 5.0.6 on 2024-07-04 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_testquiz'),
        ('subjects', '0010_alter_tests_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquiz',
            name='test_quiz',
            field=models.ManyToManyField(related_name='test_quiz', to='subjects.tests', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
