# Generated by Django 5.0.6 on 2024-07-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_testquiz_test_quiz'),
        ('subjects', '0010_alter_tests_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstsubject',
            name='first_stage',
        ),
        migrations.RemoveField(
            model_name='secondsubject',
            name='second_subject',
        ),
        migrations.AlterField(
            model_name='testquiz',
            name='test_quiz',
            field=models.ManyToManyField(related_name='test_quiz', to='subjects.tests'),
        ),
        migrations.DeleteModel(
            name='BlockTest',
        ),
        migrations.DeleteModel(
            name='FirstSubject',
        ),
        migrations.DeleteModel(
            name='SecondSubject',
        ),
    ]
