# Generated by Django 5.0.6 on 2024-07-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_firstsubject_first_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.AddField(
            model_name='testquiz',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='quiz.tag'),
        ),
    ]
