# Generated by Django 5.0.6 on 2024-07-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_tag_name_en_tag_name_ru_tag_name_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquiz',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
