# Generated by Django 5.0.6 on 2024-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_testquiz_tags_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=5000, max_length=123)),
            ],
        ),
    ]
