# Generated by Django 5.0.6 on 2024-07-30 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_blocktestprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquiz',
            name='max_point',
            field=models.FloatField(default=1.1),
        ),
        migrations.CreateModel(
            name='Mandatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matematika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matematika', to='quiz.testquiz')),
                ('ona_tili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ona_tili', to='quiz.testquiz')),
                ('tarix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarix', to='quiz.testquiz')),
            ],
        ),
    ]
