# Generated by Django 5.0.6 on 2024-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_testquiz_max_point_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktestprice',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
