# Generated by Django 5.0.6 on 2024-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
