# Generated by Django 5.0.6 on 2024-06-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.tests'),
        ),
        migrations.AddField(
            model_name='tests',
            name='body',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
