# Generated by Django 5.0.6 on 2024-06-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_answers_questions_tests_body_delete_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='unit',
            new_name='level',
        ),
    ]
