# Generated by Django 5.0.6 on 2024-06-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_rename_unit_tests_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='questions',
            new_name='test',
        ),
    ]
