# Generated by Django 5.0.6 on 2024-06-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_rename_questions_answers_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ('id', 'level'), 'verbose_name_plural': 'Tests'},
        ),
    ]
