# Generated by Django 5.0.6 on 2024-06-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_answers_options_alter_subjects_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name_plural': 'Tests'},
        ),
        migrations.AddField(
            model_name='subjects',
            name='name_en',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='name_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='subjects.subjects'),
        ),
    ]
