# Generated by Django 5.0.6 on 2024-06-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_tests_options_subjects_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_option', to='subjects.tests'),
        ),
    ]
