# Generated by Django 5.0.6 on 2024-07-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_answers_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='subjects.tests'),
        ),
    ]
