# Generated by Django 5.0.6 on 2024-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_alter_answers_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='level',
            field=models.IntegerField(choices=[(3.1, 'difficult'), (2.1, 'easy')], default=1),
        ),
    ]
