# Generated by Django 5.0.6 on 2024-07-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_alter_tests_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='level',
            field=models.FloatField(choices=[(3.1, 'difficult'), (2.1, 'easy')], default=3.1),
        ),
    ]
