# Generated by Django 5.0.6 on 2024-07-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_tests_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('name_en', models.CharField(max_length=123, null=True)),
                ('name_ru', models.CharField(max_length=123, null=True)),
                ('name_uz', models.CharField(max_length=123, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='subjects.tag'),
        ),
    ]
