# Generated by Django 5.0.6 on 2024-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_tag_subjects_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='level',
            field=models.FloatField(choices=[(3.1, 'difficult'), (1.1, 'easy')], default=3.1),
        ),
    ]
