# Generated by Django 5.0.6 on 2024-06-26 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_portfolio_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.IntegerField(blank=True, max_length=123, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
