# Generated by Django 5.0.6 on 2024-06-27 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_portfolio_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
