# Generated by Django 5.0.6 on 2024-07-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_portfolio_balance'),
        ('quiz', '0010_alter_testquiz_test_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_test', to='quiz.testquiz')),
            ],
        ),
    ]
