# Generated by Django 5.0.6 on 2024-07-18 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_maintest_author'),
        ('quiz', '0011_remove_firstsubject_first_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintest',
            name='main_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_test', to='quiz.testquiz'),
        ),
    ]
