# Generated by Django 5.0.6 on 2024-07-18 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_maintest_main_test'),
        ('quiz', '0011_remove_firstsubject_first_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintest',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintest',
            name='main_test',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='main_test', to='quiz.testquiz'),
            preserve_default=False,
        ),
    ]
