# Generated by Django 5.0.6 on 2024-07-24 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_maintest_author_alter_maintest_main_test'),
        ('subjects', '0010_alter_tests_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_test_answer', models.ManyToManyField(related_name='main_test_answer', to='subjects.tests')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='main.maintest')),
            ],
        ),
    ]
