# Generated by Django 5.0.6 on 2024-07-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mainanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainanswer',
            name='main_test_answer',
        ),
        migrations.CreateModel(
            name='TestQuiz11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_point', models.FloatField(default=2.1)),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainanswer')),
            ],
        ),
    ]
