# Generated by Django 5.0.6 on 2024-07-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_mainanswer_main_test_answer_testquiz11'),
        ('subjects', '0010_alter_tests_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainanswer',
            name='test',
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='answer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='subjects.answers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.tests'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MainAnswerQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maintest')),
            ],
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='main',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.mainanswerquiz'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestQuiz11',
        ),
    ]
