# Generated by Django 5.0.6 on 2024-07-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_mainanswer_test_mainanswer_answer_and_more'),
        ('subjects', '0010_alter_tests_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainanswer',
            name='is_answer',
        ),
        migrations.AlterField(
            model_name='mainanswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_quiz', to='subjects.tests'),
        ),
    ]
