# Generated by Django 5.0.6 on 2024-07-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_mainanswer_is_answer_alter_mainanswer_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainAnswerQuiz',
            new_name='MainAnswerBlock',
        ),
    ]
