# Generated by Django 5.0.6 on 2024-07-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_mainanswerquiz_mainanswerblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainanswer',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='main.mainanswerblock'),
        ),
    ]
