# Generated by Django 5.0.6 on 2024-07-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_mainanswer_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainanswerblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='main.maintest'),
        ),
    ]
