# Generated by Django 5.0.6 on 2024-07-30 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_portfolio_author'),
        ('quiz', '0015_blocktestprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockMainTest5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('first_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_subject', to='quiz.testquiz')),
                ('mandatory_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_subject', to='quiz.testquiz')),
                ('second_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_subject', to='quiz.testquiz')),
            ],
        ),
    ]
