# Generated by Django 5.0.6 on 2024-07-30 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_blockmaintest5'),
        ('quiz', '0016_alter_testquiz_max_point_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blockmaintest5',
            name='mandatory_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_subject', to='quiz.mandatory'),
        ),
    ]
