# Generated by Django 5.0.6 on 2024-08-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_maintest_created_date_and_more'),
        ('subjects', '0012_alter_tests_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAnswerBlock5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blockmaintest5')),
            ],
        ),
        migrations.CreateModel(
            name='MainAnswer5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.answers')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.tests')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainanswerblock5')),
            ],
        ),
    ]
