# Generated by Django 5.0.6 on 2024-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_mainanswerblock5_mainanswer5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainanswer5',
            old_name='main',
            new_name='block_test',
        ),
    ]
